name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # Zulu is recommended for Android
          java-version: '17'  # Match the Java version required for your project

      # Cache Gradle dependencies
      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # Build the project
      - name: Build the project
        run: ./gradlew assembleDebug

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Analyze the APK
      - name: Analyze APK
        run: ./gradlew lintDebug

      # Upload APK as an artifact (optional)
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
